#!/bin/bash

# Dotfiles
echo "Intalling dofiles..."
decrypt dots.tar.xz.gpg | tar xJf - --strip-components=1 -C /mnt/home/$CF_USERNAME

# Pacman
echo "Intalling packages..."
arch-chroot /mnt pacman-key --init && sudo pacman-key --populate archlinux
arch-chroot /mnt pacman -Syu
CF_PACMAN="profiles/$CF_PROFILE/pacman"
if [[ -f $CF_PACMAN && -s $CF_PACMAN ]]; then
	echo "Installing packages..."
	arch-chroot /mnt pacman -S --noconfirm $(paste -s $CF_PACMAN)
fi

# Do specific things
# ...
# ...
# ...
